### ISSUE TITLE
Nodes using Flipbook Frame Blend Type Lerp do not render

### ISSUE THREAD

**Issue by TheBroodian** [effekseer/EffekseerForGodot3#14]
When using an EffekseerEmitter (3D type) to play an effect that uses "Lerp" as its "Flipbook Frame Blend Type" do not render in Godot 3 engine.

**Comment by ueshita** [comment]
That feature does not work with Godot3.
I apologize for this limitation, which was not documented.

If you want to use flipbook frame blending, you have the option of using Godot4 or creating it in Material.

**Comment by TheBroodian** [comment]
Thank you for the info! I will find a work-around.
