### ISSUE TITLE
Looping particle emission

### ISSUE THREAD

**Issue by KennyTheBard** [effekseer/EffekseerForGodot3#3]
Is there any way to loop an emitter's run? And if not, can something like this be added in the future?

Currently, an EffekseerEmitter will finish it's assigned particles effect run and silently stops. This is quite inconvenient for repeating patterns as a Timer have to be used in order to restart it, which bring a lot of timer tweaking on the table.

Maybe emitting a signal when the emission ends or a "loop" flag in the `start` method would do the thing nicely.

Thanks for the great work!

**Comment by durswd** [comment]
There is not loop flag. But there is a method to create loop effect.

Please read it.
https://effekseer.github.io/Help_Tool/en/ToolTips/01.html#infinite-the-lifetime-of-particles

**Comment by KennyTheBard** [comment]
This indeed solves the looping problem, so i think i should close this issue. Thanks a lot!

But i still think a signal when the particle effect is finished would help a lot to synchronize things inside Godot without tweaking Timers. I will open a new issue for this one.
