### ISSUE TITLE
Godot signal for when the particle emission is finished

### ISSUE THREAD

**Issue by KennyTheBard** [effekseer/EffekseerForGodot3#4]
Exposing a signal is a very Godot-oriented way of allowing the user to synchronize the end of an emitter with some other actions.

It seems that in the current approach, the only way to do this is to know how long the emission will take and set a Timer to notify when it's done. This is less than ideal as it requires some time tweaking on each change on the effect.

Adding this (or exposing the said signal, in case it's already there) would be greatly appreciated!

**Comment by ueshita** [comment]
The "finished" signal by emitter(and 2d) is suppoerted in latest main branch.

You can wait for the next release or try the latest build of the package.
https://github.com/effekseer/EffekseerForGodot3/suites/3096404722/artifacts/70754267

**Comment by KennyTheBard** [comment]
Thank you! I had missed this. Sorry for the spam about this.

Great work!
