### ISSUE TITLE
can't reimport with opening efkefk inspector view

### ISSUE THREAD

**Issue by folt-a** [effekseer/EffekseerForGodot3#8]
1.62a

I confirmed it in windows10, ubuntu environment.

Double-click the efkefk file on Godot's file system to see the efkefk file in the Inspector view,
when I reimport, I get this error.

open the project in the Godot editor, and not display .efkefk file in the Inspector view, can reimport it.

display the efkefk file in the inspector view even once, this error occur even if the displayed contents of the inspector view are not efkefk file.
reload the project, can import again.

---

windows10, ubuntu環境で確認しました。

Godotのファイルシステム上でefkefkファイルをダブルクリックしてインスペクタビューにefkefkファイルが表示されている状態で、
再インポートを行うと、以下のようなエラーが出ます。

Godotエディタでプロジェクトを開いてから、インスペクタビューでefkefkファイルを表示しなければ正常に再インポートできます。
しかし、一度でもインスペクタビューでefkefkファイルを表示すると、インスペクタビューの表示内容をefkefkファイルでない状態にしてもエラーとなるようです。
プロジェクトリロードを行うと正常になります。

```
Another resource is loaded from path 'res://effects/effekseer/Bent_Gradiant.efkefc' (possible cyclic resource inclusion).
 Resource file not found: /texture/Bent_Gradiant_1.png.
 Error loading resource: '/texture/Bent_Gradiant_1.png'.
 Resource file not found: /model/aura.efkmodel.
 Error loading resource: '/model/aura.efkmodel'.
```
![effekreimport](https://user-images.githubusercontent.com/32963227/149649750-4488a96c-e11d-4376-90e8-02004d4f8002.png)

サブリソースのpath指定がres://ではなく/直下になるようです？
試しにubuntuの場合にファイルシステム直下、/texture/Bent_Gradiant_1.png においた場合は正常に読めました。

Dev/Cpp/src/EffekseerEffect.cppのEffekseerEffect::resolve_dependencies()にて、確認したところmaterialDirが空になっているようです。

![image](https://user-images.githubusercontent.com/32963227/149649834-491ad982-bee4-4e88-b322-b6be22ff9e50.png)

```
 Another resource is loaded from path 'res://scenes/effects/effekseer/Bent_Gradiant.efkefc' (possible cyclic resource inclusion).

/
texture/Bent_Gradiant_1.png
 Resource file not found: /texture/Bent_Gradiant_1.png.
 Error loading resource: '/texture/Bent_Gradiant_1.png'.

/
model/aura.efkmodel
 Resource file not found: /model/aura.efkmodel.
 Error loading resource: '/model/aura.efkmodel'.
```

**Comment by ueshita** [comment]
不具合の詳しい状況を報告していただき、ありがとうございます。
原因を確認して直したいと思います。

**Comment by ueshita** [comment]
こちらの問題の修正版をリリースしました。
https://github.com/effekseer/EffekseerForGodot3/releases/tag/162b

**Comment by folt-a** [comment]
再インポートが楽になりました、ありがとうございます！
